name: Upload Dotnet Package To Nuget
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Build package
      run: |
        dotnet build
        find . -type f -name "*.nupkg" -exec cp {} . \;
    - name: Publish package
      run: dotnet nuget push "*.nupkg" --api-key "${API_KEY}" --source https://api.nuget.org/v3/index.json --timeout 300
      env:
        API_KEY: ${{ secrets.API_KEY }}
