name: Test
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: |
        echo "${GITHUB_REF}"
        git describe --tags $(git rev-list --tags --max-count=1)
