name: Test
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: |
        version=$(grep -oP '(?<=<Version>)[^<]+' $(find "${GITHUB_WORKSPACE}/Services" -maxdepth 2 -mindepth 2 -type f -name *.csproj -print -quit))
        echo $version
